[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://pmpbwtxcwlmjprfmnpny.supabase.co"
  VITE_SUPABASE_ANON_KEY = ""
  VITE_SUPABASE_SERVICE_ROLE_KEY = ""

# Variables de entorno para funciones
[functions.environment]
  VITE_SUPABASE_URL = "https://pmpbwtxcwlmjprfmnpny.supabase.co"
  VITE_SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtcGJ3dHhjd2xtanByZm1ucG55Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDExODIxMCwiZXhwIjoyMDc1Njk0MjEwfQ.paste_your_service_role_key_here"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
